import argparse
import json
import time
from datetime import datetime, timezone
from collections import deque
from pathlib import Path

import cv2 as cv
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def root_path(*parts: str) -> str:
    return str(PROJECT_ROOT.joinpath(*parts))


def resolve_path(path_value: str) -> str:
    candidate = Path(path_value)
    if candidate.is_absolute():
        return str(candidate)
    return str(PROJECT_ROOT.joinpath(candidate))


def l2_normalize(v: np.ndarray) -> np.ndarray:
    norm = float(np.linalg.norm(v))
    if norm <= 1e-12:
        return v
    return v / norm


def cosine(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b))


def preprocess_for_mobilefacenet(face_bgr: np.ndarray, input_size: int) -> np.ndarray:
    face = cv.resize(face_bgr, (input_size, input_size), interpolation=cv.INTER_AREA)
    return cv.dnn.blobFromImage(
        face,
        scalefactor=1.0 / 128.0,
        size=(input_size, input_size),
        mean=(127.5, 127.5, 127.5),
        swapRB=True,
        crop=False,
    )


def iou(box_a: tuple[int, int, int, int], box_b: tuple[int, int, int, int]) -> float:
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b

    x1 = max(ax, bx)
    y1 = max(ay, by)
    x2 = min(ax + aw, bx + bw)
    y2 = min(ay + ah, by + bh)

    inter_w = max(0, x2 - x1)
    inter_h = max(0, y2 - y1)
    inter_area = inter_w * inter_h
    if inter_area == 0:
        return 0.0

    area_a = aw * ah
    area_b = bw * bh
    union = area_a + area_b - inter_area
    return inter_area / union if union > 0 else 0.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Live webcam recognition using YuNet detector + MobileFaceNet embeddings."
    )
    parser.add_argument(
        "--yunet-model",
        default=root_path("models", "yunet_mobilefacenet", "face_detection_yunet_2023mar.onnx"),
        help="Path to YuNet ONNX detector.",
    )
    parser.add_argument(
        "--mobilefacenet-model",
        default=root_path("models", "yunet_mobilefacenet", "mobilefacenet.onnx"),
        help="Path to MobileFaceNet ONNX model.",
    )
    parser.add_argument(
        "--enrollment-path",
        default=root_path("models", "yunet_mobilefacenet", "enrollment.json"),
        help="Path to enrollment JSON generated by trainer.py.",
    )
    parser.add_argument(
        "--camera-index",
        type=int,
        default=0,
        help="Webcam index for cv.VideoCapture.",
    )
    parser.add_argument(
        "--target-width",
        type=int,
        default=640,
        help="Internal resized frame width for faster detection.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=-1.0,
        help="Cosine threshold. If < 0, uses enrollment metadata recommended_threshold.",
    )
    parser.add_argument("--det-score-threshold", type=float, default=0.6)
    parser.add_argument("--det-nms-threshold", type=float, default=0.3)
    parser.add_argument("--det-top-k", type=int, default=5000)
    parser.add_argument(
        "--embed-input-size",
        type=int,
        default=0,
        help="Embedding input size. If <= 0, read from enrollment metadata (fallback 112).",
    )
    parser.add_argument(
        "--detect-every",
        type=int,
        default=2,
        help="Run detect+embed every N frames and reuse last results in between.",
    )
    parser.add_argument(
        "--largest-face-only",
        action="store_true",
        help="Only evaluate the largest detected face (faster and more stable).",
    )
    parser.add_argument(
        "--aggregate-seconds",
        type=float,
        default=3.0,
        help="Time window for vote aggregation (seconds).",
    )
    parser.add_argument(
        "--aggregate-min-hits",
        type=int,
        default=3,
        help="Minimum matched samples in the aggregation window before showing a name.",
    )
    parser.add_argument(
        "--fps-log-path",
        default=root_path("reports", "benchmark", "live_fps", "mobilefacenet_fps.jsonl"),
        help="Path to append periodic FPS samples as JSONL.",
    )
    parser.add_argument(
        "--fps-log-interval",
        type=float,
        default=1.0,
        help="Seconds between FPS log writes.",
    )
    parser.add_argument(
        "--fps-summary-dir",
        default=root_path("reports", "benchmark", "live_fps", "runs"),
        help="Directory to write per-run FPS summary JSON.",
    )
    parser.add_argument("--disable-fps-log", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.yunet_model = resolve_path(args.yunet_model)
    args.mobilefacenet_model = resolve_path(args.mobilefacenet_model)
    args.enrollment_path = resolve_path(args.enrollment_path)
    args.fps_log_path = resolve_path(args.fps_log_path)
    args.fps_summary_dir = resolve_path(args.fps_summary_dir)

    if not Path(args.yunet_model).exists():
        raise FileNotFoundError(f"YuNet model not found: {args.yunet_model}")
    if not Path(args.mobilefacenet_model).exists():
        raise FileNotFoundError(f"MobileFaceNet model not found: {args.mobilefacenet_model}")
    if not Path(args.enrollment_path).exists():
        raise FileNotFoundError(f"Enrollment file not found: {args.enrollment_path}")

    with open(args.enrollment_path, "r", encoding="utf-8") as f:
        enrollment = json.load(f)

    people_payload = enrollment.get("people", {})
    if not people_payload:
        raise RuntimeError("Enrollment JSON has no people data.")

    if args.threshold < 0:
        args.threshold = float(enrollment.get("metadata", {}).get("recommended_threshold", 0.55))

    if args.embed_input_size <= 0:
        meta = enrollment.get("metadata", {})
        args.embed_input_size = int(meta.get("training_config", {}).get("embed_input_size", 112))

    centroids = {
        person: l2_normalize(np.array(payload["centroid"], dtype=np.float32))
        for person, payload in people_payload.items()
    }
    people = sorted(centroids.keys())

    cv.setUseOptimized(True)
    detector = cv.FaceDetectorYN.create(
        args.yunet_model,
        "",
        (320, 320),
        args.det_score_threshold,
        args.det_nms_threshold,
        args.det_top_k,
    )
    embedder = cv.dnn.readNetFromONNX(args.mobilefacenet_model)

    webcam = cv.VideoCapture(args.camera_index)
    if not webcam.isOpened():
        raise RuntimeError(f"Could not open webcam index {args.camera_index}")

    print("[INFO] Press 'd' to exit.")
    print(f"[INFO] Live threshold: {args.threshold:.3f}")
    print(
        f"[INFO] Aggregation window: {max(0.5, args.aggregate_seconds):.1f}s "
        f"(min hits: {max(1, args.aggregate_min_hits)})"
    )

    detect_every = max(1, args.detect_every)
    aggregate_seconds = max(0.5, args.aggregate_seconds)
    aggregate_min_hits = max(1, args.aggregate_min_hits)

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    fps_log_interval = max(0.2, args.fps_log_interval)
    fps_log_file = None
    if not args.disable_fps_log:
        fps_log_path = Path(args.fps_log_path)
        fps_log_path.parent.mkdir(parents=True, exist_ok=True)
        fps_log_file = fps_log_path.open("a", encoding="utf-8")

    run_started = time.time()
    last_log_time = 0.0
    fps_sum = 0.0
    fps_samples = 0

    prediction_history: deque[tuple[float, str, float, bool]] = deque()
    last_primary_box: tuple[int, int, int, int] | None = None
    cached_draw_items: list[tuple[tuple[int, int, int, int], str, float, tuple[int, int, int]]] = []

    frame_count = 0
    prev_frame_time = 0.0
    fps_ema = 0.0
    displayed_fps = 0

    while True:
        ok, frame = webcam.read()
        if not ok:
            break

        h, w = frame.shape[:2]
        ratio = args.target_width / float(w)
        resized = cv.resize(frame, (args.target_width, int(h * ratio)))

        now = time.time()
        frame_time = now - prev_frame_time
        fps = 1.0 / frame_time if frame_time > 0 else 0.0
        prev_frame_time = now

        if fps_ema == 0.0:
            fps_ema = fps
        else:
            fps_ema = 0.85 * fps_ema + 0.15 * fps

        if fps > 0:
            fps_sum += fps
            fps_samples += 1

        elapsed_seconds = now - run_started
        if fps_log_file is not None and (elapsed_seconds - last_log_time) >= fps_log_interval:
            sample = {
                "run_id": run_id,
                "algorithm": "mobilefacenet",
                "elapsed_seconds": elapsed_seconds,
                "frame_count": frame_count,
                "fps": fps_ema,
            }
            fps_log_file.write(json.dumps(sample) + "\n")
            fps_log_file.flush()
            last_log_time = elapsed_seconds

        frame_count += 1
        if frame_count % 5 == 0:
            displayed_fps = int(fps_ema)

        should_detect = (frame_count % detect_every == 0) or not cached_draw_items
        if should_detect:
            rh, rw = resized.shape[:2]
            detector.setInputSize((rw, rh))
            _, faces = detector.detect(resized)

            if faces is None or len(faces) == 0:
                prediction_history.clear()
                last_primary_box = None
                cached_draw_items = []
            else:
                faces_list = list(faces)
                if args.largest_face_only:
                    faces_list = [max(faces_list, key=lambda row: float(row[2] * row[3]))]

                new_draw_items: list[
                    tuple[tuple[int, int, int, int], str, float, tuple[int, int, int]]
                ] = []

                for idx, face_row in enumerate(faces_list):
                    x, y, bw, bh = face_row[:4]
                    x1 = max(0, int(x))
                    y1 = max(0, int(y))
                    x2 = min(rw, int(x + bw))
                    y2 = min(rh, int(y + bh))
                    if x2 <= x1 or y2 <= y1:
                        continue

                    face_crop = resized[y1:y2, x1:x2]
                    blob = preprocess_for_mobilefacenet(face_crop, args.embed_input_size)
                    embedder.setInput(blob)
                    emb = l2_normalize(embedder.forward().flatten().astype(np.float32))

                    best_person = "Unknown"
                    best_score = -1.0
                    for person in people:
                        score = cosine(emb, centroids[person])
                        if score > best_score:
                            best_score = score
                            best_person = person

                    raw_is_match = best_score >= args.threshold
                    raw_name = best_person if raw_is_match else "Unknown"

                    recognized = raw_is_match
                    display_name = raw_name
                    display_score = best_score
                    current_box = (x1, y1, x2 - x1, y2 - y1)

                    use_aggregate = args.largest_face_only or len(faces_list) == 1
                    if use_aggregate and idx == 0:
                        if last_primary_box is not None and iou(last_primary_box, current_box) < 0.20:
                            prediction_history.clear()
                        last_primary_box = current_box

                        prediction_history.append((now, raw_name, float(best_score), raw_is_match))
                        cutoff = now - aggregate_seconds
                        while prediction_history and prediction_history[0][0] < cutoff:
                            prediction_history.popleft()

                        recognized = False
                        display_name = "Unknown"
                        known_hits = [h for h in prediction_history if h[3] and h[1] != "Unknown"]
                        if len(known_hits) >= aggregate_min_hits:
                            scores_by_person: dict[str, list[float]] = {}
                            for _, person_name, hit_score, _ in known_hits:
                                scores_by_person.setdefault(person_name, []).append(hit_score)

                            best_name = "Unknown"
                            best_avg = -1.0
                            best_count = -1
                            for person_name, person_scores in scores_by_person.items():
                                avg_score = sum(person_scores) / len(person_scores)
                                count = len(person_scores)
                                if avg_score > best_avg or (avg_score == best_avg and count > best_count):
                                    best_name = person_name
                                    best_avg = avg_score
                                    best_count = count

                            if best_name != "Unknown":
                                recognized = True
                                display_name = best_name
                                display_score = best_avg

                    color = (0, 255, 0) if recognized else (0, 0, 255)
                    draw_box = (
                        int(x1 / ratio),
                        int(y1 / ratio),
                        int((x2 - x1) / ratio),
                        int((y2 - y1) / ratio),
                    )
                    new_draw_items.append((draw_box, display_name, display_score, color))

                cached_draw_items = new_draw_items

        for draw_box, name, score, color in cached_draw_items:
            x, y, bw, bh = draw_box
            cv.rectangle(frame, (x, y), (x + bw, y + bh), color, 2)
            cv.putText(
                frame,
                f"{name} ({score:.2f})",
                (x, max(0, y - 10)),
                cv.FONT_HERSHEY_COMPLEX,
                0.6,
                (255, 255, 255),
                2,
                cv.LINE_AA,
            )

        cv.putText(
            frame,
            f"FPS: {displayed_fps}",
            (10, 30),
            cv.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
        )
        cv.imshow("YuNet + MobileFaceNet Live", frame)

        if cv.waitKey(1) & 0xFF == ord("d"):
            break

    webcam.release()
    cv.destroyAllWindows()

    total_seconds = max(0.0, time.time() - run_started)
    avg_fps = (fps_sum / fps_samples) if fps_samples else 0.0

    Path(args.fps_summary_dir).mkdir(parents=True, exist_ok=True)
    summary_path = Path(args.fps_summary_dir) / f"mobilefacenet_{run_id}.json"
    summary_payload = {
        "run_id": run_id,
        "algorithm": "mobilefacenet",
        "average_fps": avg_fps,
        "frames": frame_count,
        "duration_seconds": total_seconds,
        "threshold": args.threshold,
    }
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary_payload, f, indent=2)

    if fps_log_file is not None:
        fps_log_file.close()

    print(f"[FPS] Average FPS: {avg_fps:.2f}")
    print(f"[FPS] Summary: {summary_path}")


if __name__ == "__main__":
    main()
