import argparse
from collections import Counter, deque
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import cv2 as cv
import numpy as np

from src.classical_faces.detection import create_face_detector, resolve_default_backend
from src.classical_faces.pipeline import SPECS
from src.lbph.preprocess import IMG_SIZE, normalize_face, resolve_eye_cascade_path, align_face_by_eyes

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SPEC = SPECS["lbph"]


def root_path(*parts: str) -> str:
    return str(PROJECT_ROOT.joinpath(*parts))


def resolve_path(path_value: str) -> str:
    candidate = Path(path_value)
    if candidate.is_absolute():
        return str(candidate)
    return str(PROJECT_ROOT.joinpath(candidate))


def iou(box_a: tuple[int, int, int, int], box_b: tuple[int, int, int, int]) -> float:
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b

    x1 = max(ax, bx)
    y1 = max(ay, by)
    x2 = min(ax + aw, bx + bw)
    y2 = min(ay + ah, by + bh)

    inter_w = max(0, x2 - x1)
    inter_h = max(0, y2 - y1)
    inter_area = inter_w * inter_h
    if inter_area == 0:
        return 0.0

    area_a = aw * ah
    area_b = bw * bh
    union = area_a + area_b - inter_area
    return inter_area / union if union > 0 else 0.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Live face detection and recognition using trained LBPH model."
    )
    parser.add_argument(
        "--model-path",
        default=root_path("models", "lbph", "lasalle_clean.yml"),
        help="Path to trained LBPH model.",
    )
    parser.add_argument(
        "--labels-path",
        default=root_path("models", "lbph", "labels_lasalle_clean.json"),
        help="Path to labels JSON generated by trainer.py.",
    )
    parser.add_argument(
        "--cascade-path",
        default=root_path("haar", "haarcascade_frontalface_default.xml"),
        help="Path to Haar cascade XML.",
    )
    parser.add_argument(
        "--eye-cascade-path",
        default="",
        help="Optional path to Haar eye cascade XML. If empty, OpenCV default is used.",
    )
    parser.add_argument(
        "--detector",
        choices=["haar", "yunet"],
        default=resolve_default_backend(),
        help="Face detection backend: 'haar' (Viola-Jones) or 'yunet' (CNN). "
        "Default from the FACE_G3_DETECTOR env var, else 'haar'.",
    )
    parser.add_argument(
        "--yunet-model-path",
        default="",
        help="YuNet ONNX weights (default: models/yunet_mobilefacenet/face_detection_yunet_2023mar.onnx).",
    )
    parser.add_argument("--yunet-score-threshold", type=float, default=0.6)
    parser.add_argument("--yunet-nms-threshold", type=float, default=0.3)
    parser.add_argument(
        "--camera-index",
        type=int,
        default=0,
        help="Webcam index for cv.VideoCapture.",
    )
    parser.add_argument(
        "--target-width",
        type=int,
        default=0,
        help="Deprecated compatibility flag. Use --downscale-max-side instead.",
    )
    parser.add_argument(
        "--downscale-max-side",
        type=int,
        default=640,
        help="Longest side for detection frames; 0 disables downscaling.",
    )
    parser.add_argument(
        "--unknown-threshold",
        type=float,
        default=SPEC.default_unknown_threshold,
        help="LBPH distance threshold; lower is stricter.",
    )
    parser.add_argument(
        "--min-face-size",
        type=int,
        default=72,
        help="Minimum face size for detection.",
    )
    parser.add_argument(
        "--scale-factor",
        type=float,
        default=1.15,
        help="Scale factor for Haar detectMultiScale.",
    )
    parser.add_argument(
        "--min-neighbors",
        type=int,
        default=8,
        help="Min neighbors for Haar detectMultiScale.",
    )
    parser.add_argument(
        "--detect-every",
        type=int,
        default=3,
        help="Run full-frame detection every N frames.",
    )
    parser.add_argument(
        "--track-between-detections",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use optical flow to track a face between detector passes.",
    )
    parser.add_argument(
        "--largest-face-only",
        action="store_true",
        help="Only evaluate the largest detected face.",
    )
    parser.add_argument(
        "--align-eyes",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Eye-based alignment before equalize/resize. Off by default to match the "
             "clean La Salle model (trained without alignment). Enable for raw/aligned models.",
    )
    parser.add_argument(
        "--equalization",
        choices=["equalize", "clahe", "tan-triggs"],
        default=SPEC.default_equalization,
        help="Face contrast normalization (default matches how the clean model was trained).",
    )
    parser.add_argument(
        "--temporal-window",
        type=int,
        default=5,
        help="Prediction smoothing window size in frames.",
    )
    parser.add_argument(
        "--min-stable-hits",
        type=int,
        default=3,
        help="Required consistent hits in temporal window before showing a name.",
    )
    parser.add_argument(
        "--min-stable-frames",
        type=int,
        default=2,
        help="Minimum tracked/detected frames before recognition is accepted.",
    )
    parser.add_argument(
        "--fps-log-path",
        default=root_path("reports", "benchmark", "live_fps", "lbph_fps.jsonl"),
        help="Path to append periodic FPS samples as JSONL.",
    )
    parser.add_argument(
        "--fps-log-interval",
        type=float,
        default=1.0,
        help="Seconds between FPS log writes.",
    )
    parser.add_argument(
        "--fps-summary-dir",
        default=root_path("reports", "benchmark", "live_fps", "runs"),
        help="Directory to write per-run FPS summary JSON.",
    )
    parser.add_argument(
        "--session-log-json",
        default="",
        help="Optional JSON path to write a per-session live metrics summary.",
    )
    parser.add_argument("--disable-fps-log", action="store_true")
    return parser.parse_args()


def clamp_box(box, width: int, height: int):
    x, y, w, h = box
    x = max(0, min(x, width - 1))
    y = max(0, min(y, height - 1))
    w = max(1, min(w, width - x))
    h = max(1, min(h, height - y))
    return x, y, w, h


def box_to_points(box):
    x, y, w, h = box
    return np.array(
        [[[x, y]], [[x + w, y]], [[x + w, y + h]], [[x, y + h]]],
        dtype="float32",
    )


def points_to_box(points, width: int, height: int):
    pts = points.reshape(-1, 2)
    x_min = int(max(0, min(pts[:, 0])))
    y_min = int(max(0, min(pts[:, 1])))
    x_max = int(min(width - 1, max(pts[:, 0])))
    y_max = int(min(height - 1, max(pts[:, 1])))
    return clamp_box((x_min, y_min, max(1, x_max - x_min), max(1, y_max - y_min)), width, height)


def main() -> None:
    args = parse_args()
    args.model_path = resolve_path(args.model_path)
    args.labels_path = resolve_path(args.labels_path)
    args.cascade_path = resolve_path(args.cascade_path)
    args.eye_cascade_path = resolve_path(resolve_eye_cascade_path(args.eye_cascade_path))
    args.fps_log_path = resolve_path(args.fps_log_path)
    args.fps_summary_dir = resolve_path(args.fps_summary_dir)
    if args.session_log_json:
        args.session_log_json = resolve_path(args.session_log_json)

    if args.target_width > 0 and args.downscale_max_side <= 0:
        args.downscale_max_side = args.target_width

    cv.setUseOptimized(True)

    detector = create_face_detector(
        args.detector,
        cascade_path=args.cascade_path,
        yunet_model_path=args.yunet_model_path or None,
        min_face_size=args.min_face_size,
        scale_factor=args.scale_factor,
        min_neighbors=args.min_neighbors,
        downscale_max_side=args.downscale_max_side,
        yunet_score_threshold=args.yunet_score_threshold,
        yunet_nms_threshold=args.yunet_nms_threshold,
    )
    print(f"[INFO] Face detector: {detector.describe()}")

    eye_cascade: cv.CascadeClassifier | None = None
    if args.align_eyes:
        eye_cascade = cv.CascadeClassifier(args.eye_cascade_path)
        if eye_cascade.empty():
            print(
                f"[WARN] Could not load eye cascade at {args.eye_cascade_path}. "
                "Alignment will be disabled."
            )
            eye_cascade = None

    recognizer = cv.face.LBPHFaceRecognizer_create()
    recognizer.read(args.model_path)

    with open(args.labels_path, "r", encoding="utf-8") as f:
        labels_raw = json.load(f)

    id_to_name = {int(idx): name for name, idx in labels_raw.items()}

    webcam = cv.VideoCapture(args.camera_index)
    if not webcam.isOpened():
        raise RuntimeError(f"Could not open webcam index {args.camera_index}")

    print("[INFO] Press 'd' to exit.")

    detect_every = max(1, args.detect_every)
    temporal_window = max(1, args.temporal_window)
    min_stable_hits = max(1, min(args.min_stable_hits, temporal_window))
    min_stable_frames = max(1, args.min_stable_frames)

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    fps_log_interval = max(0.2, args.fps_log_interval)

    fps_log_file = None
    if not args.disable_fps_log:
        fps_log_path = Path(args.fps_log_path)
        fps_log_path.parent.mkdir(parents=True, exist_ok=True)
        fps_log_file = fps_log_path.open("a", encoding="utf-8")

    run_started = time.time()
    last_log_time = 0.0

    frame_count = 0
    detection_count = 0
    recognition_count = 0
    track_updates = 0
    fps_sum = 0.0
    fps_samples = 0

    previous_frame_time = time.time()
    fps_ema = 0.0
    rec_fps_ema = 0.0
    rec_tick_last = time.time()
    rec_tick_count = 0

    prediction_history: deque[tuple[str, float, bool]] = deque(maxlen=temporal_window)
    tracked_box: tuple[int, int, int, int] | None = None
    track_points = None
    stable_frames = 0

    prev_gray = None
    current_label = "Unknown"
    current_distance = -1.0
    current_confidence = 0.0

    while True:
        ret, frame = webcam.read()
        if not ret:
            break

        frame_count += 1
        now = time.time()
        delta = now - previous_frame_time
        previous_frame_time = now
        fps = (1.0 / delta) if delta > 0 else 0.0
        fps_ema = fps if fps_ema == 0.0 else 0.85 * fps_ema + 0.15 * fps
        if fps > 0:
            fps_sum += fps
            fps_samples += 1

        gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        h, w = gray.shape[:2]

        updated_by_tracking = False
        if (
            args.track_between_detections
            and tracked_box is not None
            and track_points is not None
            and prev_gray is not None
            and (frame_count % detect_every) != 0
        ):
            next_points, status, _ = cv.calcOpticalFlowPyrLK(prev_gray, gray, track_points, None)
            if next_points is not None and status is not None:
                good_new = next_points[status.flatten() == 1]
                if len(good_new) >= 3:
                    new_box = points_to_box(good_new.reshape(-1, 1, 2), w, h)
                    if iou(tracked_box, new_box) > 0.05:
                        tracked_box = new_box
                        track_points = good_new.reshape(-1, 1, 2).astype("float32")
                        stable_frames += 1
                        updated_by_tracking = True
                        track_updates += 1

        need_detect = (frame_count % detect_every == 0) or (tracked_box is None)
        if need_detect and not updated_by_tracking:
            # YuNet uses the BGR frame for best accuracy; Haar ignores it (gray).
            face_box = detector.detect_largest(gray, image_bgr=frame)
            detection_count += 1
            if face_box is None:
                tracked_box = None
                track_points = None
                prediction_history.clear()
                stable_frames = 0
                current_label = "Unknown"
                current_distance = -1.0
                current_confidence = 0.0
            else:
                tracked_box = clamp_box(face_box, w, h)
                track_points = box_to_points(tracked_box)
                stable_frames = 1

        if tracked_box is not None and stable_frames >= min_stable_frames:
            x, y, fw, fh = clamp_box(tracked_box, w, h)
            roi = gray[y : y + fh, x : x + fw]

            if roi.size > 0:
                aligned = False
                if args.align_eyes and eye_cascade is not None and not eye_cascade.empty():
                    roi, aligned = align_face_by_eyes(roi, eye_cascade)

                processed = normalize_face(roi, img_size=IMG_SIZE, equalization=args.equalization)
                pred_id, distance = recognizer.predict(processed)
                raw_match = distance <= args.unknown_threshold
                raw_name = id_to_name.get(pred_id, "Unknown") if raw_match else "Unknown"
                prediction_history.append((raw_name, float(distance), raw_match))

                recognized = False
                label = "Unknown"
                display_distance = float(distance)

                stable_hits = [h for h in prediction_history if h[2] and h[0] != "Unknown"]
                if len(stable_hits) >= min_stable_hits:
                    top_name, top_count = Counter(h[0] for h in stable_hits).most_common(1)[0]
                    if top_count >= min_stable_hits:
                        same_name_dist = [h[1] for h in stable_hits if h[0] == top_name]
                        recognized = True
                        label = top_name
                        display_distance = sum(same_name_dist) / len(same_name_dist)

                current_label = label if recognized else "Unknown"
                current_distance = display_distance
                current_confidence = max(
                    0.0,
                    min(100.0, 100.0 * (1.0 - (display_distance / max(1.0, args.unknown_threshold)))),
                )

                recognition_count += 1
                rec_tick_count += 1

                if (now - rec_tick_last) >= 1.0:
                    recent_rec_fps = rec_tick_count / max(1e-6, now - rec_tick_last)
                    rec_fps_ema = (
                        recent_rec_fps
                        if rec_fps_ema == 0.0
                        else 0.80 * rec_fps_ema + 0.20 * recent_rec_fps
                    )
                    rec_tick_last = now
                    rec_tick_count = 0

                box_color = (0, 255, 0) if current_label != "Unknown" else (0, 0, 255)
                cv.rectangle(frame, (x, y), (x + fw, y + fh), box_color, 2)

                align_tag = "A" if aligned else "NA"
                cv.putText(
                    frame,
                    f"{current_label} d={current_distance:.1f} conf={current_confidence:.1f}% {align_tag}",
                    (x, max(0, y - 10)),
                    cv.FONT_HERSHEY_COMPLEX,
                    0.55,
                    (255, 255, 255),
                    2,
                    cv.LINE_AA,
                )

        elapsed_seconds = now - run_started
        if fps_log_file is not None and (elapsed_seconds - last_log_time) >= fps_log_interval:
            sample = {
                "run_id": run_id,
                "algorithm": "lbph",
                "elapsed_seconds": elapsed_seconds,
                "frame_count": frame_count,
                "fps": fps_ema,
                "recognition_fps": rec_fps_ema,
                "detections": detection_count,
                "recognitions": recognition_count,
            }
            fps_log_file.write(json.dumps(sample) + "\n")
            fps_log_file.flush()
            last_log_time = elapsed_seconds

        cv.putText(
            frame,
            f"FPS {fps_ema:.1f} | RecFPS {rec_fps_ema:.1f} | DetectInt {detect_every}",
            (10, 30),
            cv.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 255, 0),
            2,
        )
        cv.putText(
            frame,
            f"ID {current_label} | Dist {current_distance:.1f} | Thr {args.unknown_threshold:.1f}",
            (10, 58),
            cv.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 255, 255),
            2,
        )

        cv.imshow("Camera Output", frame)
        prev_gray = gray

        if cv.waitKey(1) & 0xFF == ord("d"):
            break

    webcam.release()
    cv.destroyAllWindows()

    total_seconds = max(0.0, time.time() - run_started)
    avg_fps = (fps_sum / fps_samples) if fps_samples else 0.0
    avg_rec_fps = (recognition_count / total_seconds) if total_seconds > 0 else 0.0

    Path(args.fps_summary_dir).mkdir(parents=True, exist_ok=True)
    summary_path = Path(args.fps_summary_dir) / f"lbph_{run_id}.json"
    summary_payload = {
        "run_id": run_id,
        "algorithm": "lbph",
        "detector": args.detector,
        "average_fps": avg_fps,
        "average_recognition_fps": avg_rec_fps,
        "frames": frame_count,
        "detections": detection_count,
        "recognitions": recognition_count,
        "tracking_updates": track_updates,
        "duration_seconds": total_seconds,
        "unknown_threshold": args.unknown_threshold,
        "detect_every": detect_every,
        "downscale_max_side": args.downscale_max_side,
        "align_eyes": args.align_eyes,
    }
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary_payload, f, indent=2)

    if args.session_log_json:
        Path(args.session_log_json).parent.mkdir(parents=True, exist_ok=True)
        with open(args.session_log_json, "w", encoding="utf-8") as f:
            json.dump(summary_payload, f, indent=2)

    if fps_log_file is not None:
        fps_log_file.close()

    print(f"[FPS] Average FPS: {avg_fps:.2f}")
    print(f"[FPS] Average recognition FPS: {avg_rec_fps:.2f}")
    print(f"[FPS] Summary: {summary_path}")


if __name__ == "__main__":
    main()
