import argparse
from collections import Counter, deque
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import cv2 as cv

from src.classical_faces.detection import create_face_detector, resolve_default_backend
from src.classical_faces.pipeline import SPECS
from src.classical_faces.preprocess import IMG_SIZE, normalize_face

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SPEC = SPECS["eigenfaces"]


def root_path(*parts: str) -> str:
    return str(PROJECT_ROOT.joinpath(*parts))


def resolve_path(path_value: str) -> str:
    candidate = Path(path_value)
    if candidate.is_absolute():
        return str(candidate)
    return str(PROJECT_ROOT.joinpath(candidate))


def iou(box_a: tuple[int, int, int, int], box_b: tuple[int, int, int, int]) -> float:
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b

    x1 = max(ax, bx)
    y1 = max(ay, by)
    x2 = min(ax + aw, bx + bw)
    y2 = min(ay + ah, by + bh)

    inter_w = max(0, x2 - x1)
    inter_h = max(0, y2 - y1)
    inter_area = inter_w * inter_h
    if inter_area == 0:
        return 0.0

    area_a = aw * ah
    area_b = bw * bh
    union = area_a + area_b - inter_area
    return inter_area / union if union > 0 else 0.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Live face detection and recognition using trained Eigenfaces model."
    )
    parser.add_argument(
        "--model-path",
        default=root_path("models", "eigenfaces", "lasalle_clean.yml"),
        help="Path to trained Eigenfaces model.",
    )
    parser.add_argument(
        "--labels-path",
        default=root_path("models", "eigenfaces", "labels_lasalle_clean.json"),
        help="Path to labels JSON generated by trainer.py.",
    )
    parser.add_argument(
        "--cascade-path",
        default=root_path("haar", "haarcascade_frontalface_default.xml"),
        help="Path to Haar cascade XML.",
    )
    parser.add_argument(
        "--detector",
        choices=["haar", "yunet"],
        default=resolve_default_backend(),
        help="Face detection backend: 'haar' (Viola-Jones) or 'yunet' (CNN). "
        "Default from the FACE_G3_DETECTOR env var, else 'haar'.",
    )
    parser.add_argument(
        "--yunet-model-path",
        default="",
        help="YuNet ONNX weights (default: models/yunet_mobilefacenet/face_detection_yunet_2023mar.onnx).",
    )
    parser.add_argument("--yunet-score-threshold", type=float, default=0.6)
    parser.add_argument("--yunet-nms-threshold", type=float, default=0.3)
    parser.add_argument(
        "--camera-index",
        type=int,
        default=0,
        help="Webcam index for cv.VideoCapture.",
    )
    parser.add_argument(
        "--target-width",
        type=int,
        default=384,
        help="Internal resized frame width for faster detection.",
    )
    parser.add_argument(
        "--unknown-threshold",
        type=float,
        default=SPEC.default_unknown_threshold,
        help="Eigenfaces confidence threshold; lower is stricter, higher is more permissive.",
    )
    parser.add_argument(
        "--equalization",
        choices=["equalize", "clahe", "tan-triggs"],
        default=SPEC.default_equalization,
        help="Face contrast normalization (default matches how the clean model was trained).",
    )
    parser.add_argument(
        "--min-face-size",
        type=int,
        default=72,
        help="Minimum face size for detection.",
    )
    parser.add_argument(
        "--scale-factor",
        type=float,
        default=1.15,
        help="Scale factor for Haar detectMultiScale (higher is usually faster, less sensitive).",
    )
    parser.add_argument(
        "--min-neighbors",
        type=int,
        default=8,
        help="Min neighbors for Haar detectMultiScale (higher reduces false positives).",
    )
    parser.add_argument(
        "--detect-every",
        type=int,
        default=2,
        help="Run detect+predict every N frames and reuse last results in between.",
    )
    parser.add_argument(
        "--largest-face-only",
        action="store_true",
        help="Only evaluate the largest detected face (faster and usually more stable).",
    )
    parser.add_argument(
        "--temporal-window",
        type=int,
        default=5,
        help="Prediction smoothing window size in frames.",
    )
    parser.add_argument(
        "--min-stable-hits",
        type=int,
        default=3,
        help="Required consistent hits in temporal window before showing a name.",
    )
    parser.add_argument(
        "--fps-log-path",
        default=root_path("reports", "benchmark", "live_fps", "eigenfaces_fps.jsonl"),
        help="Path to append periodic FPS samples as JSONL.",
    )
    parser.add_argument(
        "--fps-log-interval",
        type=float,
        default=1.0,
        help="Seconds between FPS log writes.",
    )
    parser.add_argument(
        "--fps-summary-dir",
        default=root_path("reports", "benchmark", "live_fps", "runs"),
        help="Directory to write per-run FPS summary JSON.",
    )
    parser.add_argument("--disable-fps-log", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.model_path = resolve_path(args.model_path)
    args.labels_path = resolve_path(args.labels_path)
    args.cascade_path = resolve_path(args.cascade_path)
    args.fps_log_path = resolve_path(args.fps_log_path)
    args.fps_summary_dir = resolve_path(args.fps_summary_dir)

    cv.setUseOptimized(True)

    # Frame is resized to target_width below, so the detector does no further
    # downscale (downscale_max_side=0). Toggle Haar <-> YuNet with --detector.
    detector = create_face_detector(
        args.detector,
        cascade_path=args.cascade_path,
        yunet_model_path=args.yunet_model_path or None,
        min_face_size=args.min_face_size,
        scale_factor=args.scale_factor,
        min_neighbors=args.min_neighbors,
        downscale_max_side=0,
        yunet_score_threshold=args.yunet_score_threshold,
        yunet_nms_threshold=args.yunet_nms_threshold,
    )
    print(f"[INFO] Face detector: {detector.describe()}")

    recognizer = cv.face.EigenFaceRecognizer_create()
    recognizer.read(args.model_path)

    with open(args.labels_path, "r", encoding="utf-8") as f:
        labels_raw = json.load(f)

    id_to_name = {int(idx): name for name, idx in labels_raw.items()}

    webcam = cv.VideoCapture(args.camera_index)
    if not webcam.isOpened():
        raise RuntimeError(f"Could not open webcam index {args.camera_index}")

    print("[INFO] Press 'd' to exit.")

    prev_frame_time = 0.0
    displayed_fps = 0
    frame_count = 0
    fps_ema = 0.0

    detect_every = max(1, args.detect_every)
    temporal_window = max(1, args.temporal_window)
    min_stable_hits = max(1, min(args.min_stable_hits, temporal_window))

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    fps_log_interval = max(0.2, args.fps_log_interval)
    fps_log_file = None
    if not args.disable_fps_log:
        fps_log_path = Path(args.fps_log_path)
        fps_log_path.parent.mkdir(parents=True, exist_ok=True)
        fps_log_file = fps_log_path.open("a", encoding="utf-8")

    run_started = time.time()
    last_log_time = 0.0
    fps_sum = 0.0
    fps_samples = 0

    prediction_history: deque[tuple[str, float, bool]] = deque(maxlen=temporal_window)
    last_primary_box: tuple[int, int, int, int] | None = None
    cached_draw_items: list[tuple[tuple[int, int, int, int], str, float, tuple[int, int, int]]] = []

    while True:
        ret, frame = webcam.read()
        if not ret:
            break

        height, width = frame.shape[:2]
        ratio = args.target_width / float(width)
        resized = cv.resize(frame, (args.target_width, int(height * ratio)))

        now = time.time()
        frame_time = now - prev_frame_time
        fps = 1.0 / frame_time if frame_time > 0 else 0.0
        prev_frame_time = now

        if fps_ema == 0.0:
            fps_ema = fps
        else:
            fps_ema = 0.85 * fps_ema + 0.15 * fps

        if fps > 0:
            fps_sum += fps
            fps_samples += 1

        elapsed_seconds = now - run_started
        if fps_log_file is not None and (elapsed_seconds - last_log_time) >= fps_log_interval:
            sample = {
                "run_id": run_id,
                "algorithm": "eigenfaces",
                "elapsed_seconds": elapsed_seconds,
                "frame_count": frame_count,
                "fps": fps_ema,
            }
            fps_log_file.write(json.dumps(sample) + "\n")
            fps_log_file.flush()
            last_log_time = elapsed_seconds

        frame_count += 1
        if frame_count % 5 == 0:
            displayed_fps = int(fps_ema)

        should_detect = (frame_count % detect_every == 0) or not cached_draw_items
        if should_detect:
            # Detect on raw grayscale (as training does); normalization is applied
            # per detected ROI below so live input matches the trained distribution.
            gray = cv.cvtColor(resized, cv.COLOR_BGR2GRAY)

            # YuNet uses the BGR frame; Haar ignores it. Boxes are in resized-frame coords.
            faces = [d.box for d in detector.detect(gray, image_bgr=resized)]

            if len(faces) == 0:
                prediction_history.clear()
                last_primary_box = None
                cached_draw_items = []
            else:
                faces_list = list(faces)
                if args.largest_face_only:
                    faces_list = [max(faces_list, key=lambda b: b[2] * b[3])]

                new_draw_items: list[
                    tuple[tuple[int, int, int, int], str, float, tuple[int, int, int]]
                ] = []

                for (x, y, w, h) in faces_list:
                    roi = gray[y : y + h, x : x + w]
                    if roi.size == 0:
                        continue

                    current_box = (int(x), int(y), int(w), int(h))
                    if last_primary_box is not None and iou(last_primary_box, current_box) < 0.20:
                        prediction_history.clear()
                    last_primary_box = current_box

                    face_input = normalize_face(roi, img_size=IMG_SIZE, equalization=args.equalization)
                    label_id, distance = recognizer.predict(face_input)

                    is_raw_match = distance <= args.unknown_threshold
                    raw_name = id_to_name.get(label_id, "Unknown") if is_raw_match else "Unknown"
                    prediction_history.append((raw_name, float(distance), is_raw_match))

                    recognized = False
                    name = "Unknown"
                    display_distance = float(distance)

                    stable_hits = [h for h in prediction_history if h[2] and h[0] != "Unknown"]
                    if len(stable_hits) >= min_stable_hits:
                        top_name, top_count = Counter(h[0] for h in stable_hits).most_common(1)[0]
                        if top_count >= min_stable_hits:
                            same_name_dist = [h[1] for h in stable_hits if h[0] == top_name]
                            recognized = True
                            name = top_name
                            display_distance = sum(same_name_dist) / len(same_name_dist)

                    color = (0, 255, 0) if recognized else (0, 0, 255)

                    orig_x, orig_y = int(x / ratio), int(y / ratio)
                    orig_w, orig_h = int(w / ratio), int(h / ratio)
                    draw_box = (orig_x, orig_y, orig_w, orig_h)
                    new_draw_items.append((draw_box, name, display_distance, color))

                cached_draw_items = new_draw_items

        for (draw_box, name, display_distance, color) in cached_draw_items:
            orig_x, orig_y, orig_w, orig_h = draw_box
            cv.rectangle(
                frame,
                (orig_x, orig_y),
                (orig_x + orig_w, orig_y + orig_h),
                color,
                2,
            )
            cv.putText(
                frame,
                f"{name} ({display_distance:.1f})",
                (orig_x, max(0, orig_y - 10)),
                cv.FONT_HERSHEY_COMPLEX,
                0.6,
                (255, 255, 255),
                2,
                cv.LINE_AA,
            )

        cv.putText(
            frame,
            f"FPS: {displayed_fps}",
            (10, 30),
            cv.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 0),
            2,
        )

        cv.imshow("Camera Output (Eigenfaces)", frame)

        if cv.waitKey(1) & 0xFF == ord("d"):
            break

    webcam.release()
    cv.destroyAllWindows()

    total_seconds = max(0.0, time.time() - run_started)
    avg_fps = (fps_sum / fps_samples) if fps_samples else 0.0

    Path(args.fps_summary_dir).mkdir(parents=True, exist_ok=True)
    summary_path = Path(args.fps_summary_dir) / f"eigenfaces_{run_id}.json"
    summary_payload = {
        "run_id": run_id,
        "algorithm": "eigenfaces",
        "detector": args.detector,
        "average_fps": avg_fps,
        "frames": frame_count,
        "duration_seconds": total_seconds,
        "unknown_threshold": args.unknown_threshold,
    }
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary_payload, f, indent=2)

    if fps_log_file is not None:
        fps_log_file.close()

    print(f"[FPS] Average FPS: {avg_fps:.2f}")
    print(f"[FPS] Summary: {summary_path}")


if __name__ == "__main__":
    main()
